export enum IdList {
  WelcomeVtrs = "welcome-vtrs",
  VtrsToken = "vtrs-token",
  PresaleState = "final-stage",
  PresaleBuy = "how-to-buy-vtrs",
  PresaleStructure = "presale-structure",
  PresaleProposed = "tokenomics",
  WelocmeEcosystem = "welcome-ecosystem",
  Vnrg = "vtrs-ecosystem-and-vnrg",
  VtrsChain = "vtrs-chain",
  AppCards = "vtrs-cards",
  VGovern = "v-govern",
  StakingVtrs = "staking-vtrs",
  VipAndVipp = "vip-and-vipp",
  Collaborative = "collaborative-staking",
  Manifesto = "manifesto",
  Policies = "policies",
  VtrsFaq = "vtrs-faq",
  Helpdesk = "helpdesk",
  WelocmeCompany = "contacts",
  Blog = "blog",
}
