export enum RoutesNames {
  Home = "/",
  NotFound = "/not-found",
  Vtrs = "/vtrs",
  Ecosystem = "/ecosystem",
  EarningPrograms = "/earning-programs",
  //Shop = "/shop",
  Documents = "/documents",
  Faq = "/faq",
  Blog = "/blog",
  Company = "/company",
  Support = "/support",
  Statement = "/statement",
  Terms = "/terms",
  Imprint = "/imprint",
  VappTerms = "/vapp-terms-of-use",
  WebsiteTerms = "/website-terms-of-use",
  VnodeTerms = "/vnode-terms-of-use",
}
